import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CevaLog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <div className="w-full h-full fixed z-[-1]">
        <Image src="/image/pexels-suzyhazelwood-1098515.jpg"
      alt="Image Fond Globe"
      width={0}
      height={0}
      
      layout="fill"
      objectFit="cover"
      
      /></div>{children}</body>

    </html>
  );
}



  
